SET AUTOCOMMIT FALSE;
INSERT INTO Product(id,name,type,description,img_url,price,inventory) VALUES (NEXT VALUE FOR hibernate_sequence, 'HP Pavillion', 'LAPTOP', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet mauris semper, interdum sem lobortis, commodo magna. Donec porttitor eu sapien ac imperdiet. Aenean volutpat hendrerit purus. Donec accumsan nec arcu vel pretium. Sed erat mi, euismod at euismod quis, ultrices nec dui. Fusce commodo purus ac urna dignissim, ut eleifend ipsum sagittis. Curabitur a sapien id libero convallis porta ac nec est. Nullam vitae convallis nisl. Sed turpis velit, facilisis ac massa cursus, pellentesque tincidunt risus.', 'hp-pavilion156.jpg', 339.49, 29);

INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.screen', '15.6 in 1366 &times; 768');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.cpu', 'Intel Core i5 2.2GHz 3MB cache');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.ram', '6GB DDR3L SDRAM');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.hdd', '1TB 5400RPM');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.graphics', 'Radeon M6900 1GB');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.audio', ' B&O PLAY with dual speakers');

INSERT INTO Product(id,name,type,description,img_url,price,inventory) VALUES (NEXT VALUE FOR hibernate_sequence, 'ASUS X555LA', 'LAPTOP', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet mauris semper, interdum sem lobortis, commodo magna. Donec porttitor eu sapien ac imperdiet. Aenean volutpat hendrerit purus. Donec accumsan nec arcu vel pretium. Sed erat mi, euismod at euismod quis, ultrices nec dui. Fusce commodo purus ac urna dignissim, ut eleifend ipsum sagittis. Curabitur a sapien id libero convallis porta ac nec est. Nullam vitae convallis nisl. Sed turpis velit, facilisis ac massa cursus, pellentesque tincidunt risus.', 'asus-x555la.jpg', 749.55, 3);

INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.screen', '15.6 in 1366 &times; 768');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.cpu', 'Intel Core i5-5200U 2.5 GHz 3MB cache');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.ram', '12 GB DDR3L 1600 MHz');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.hdd', '1TB 5400RPM');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.graphics', 'Intel HD Integrated');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.audio', ' Standard');

INSERT INTO Product(id,name,type,description,img_url,price,inventory) VALUES (NEXT VALUE FOR hibernate_sequence, 'LG G5', 'PHONE', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet mauris semper, interdum sem lobortis, commodo magna. Donec porttitor eu sapien ac imperdiet. Aenean volutpat hendrerit purus. Donec accumsan nec arcu vel pretium. Sed erat mi, euismod at euismod quis, ultrices nec dui. Fusce commodo purus ac urna dignissim, ut eleifend ipsum sagittis. Curabitur a sapien id libero convallis porta ac nec est. Nullam vitae convallis nisl. Sed turpis velit, facilisis ac massa cursus, pellentesque tincidunt risus.', 'lg-g5.jpg', 314.99, 10);

INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.screen', 'TFT LCD 2560 &times; 1440');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.cpu', ' Qualcomm MSM8996');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.ram', '4 GB');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.size', '14.94 &times; 7.39 &times; 0.73 (cm)');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.cam', ' 16 MP, Resolution 3840 &times; 2160');

INSERT INTO Product(id,name,type,description,img_url,price,inventory) VALUES (NEXT VALUE FOR hibernate_sequence, 'Lenovo IdeaPad', 'LAPTOP', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet mauris semper, interdum sem lobortis, commodo magna. Donec porttitor eu sapien ac imperdiet. Aenean volutpat hendrerit purus. Donec accumsan nec arcu vel pretium. Sed erat mi, euismod at euismod quis, ultrices nec dui. Fusce commodo purus ac urna dignissim, ut eleifend ipsum sagittis. Curabitur a sapien id libero convallis porta ac nec est. Nullam vitae convallis nisl. Sed turpis velit, facilisis ac massa cursus, pellentesque tincidunt risus.', 'lenovo-ideapad.jpg', 603.00, 0);

INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.screen', '15.6 in 1366 &times; 768');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.cpu', 'Intel Core i3-5020U 2.2 GHz 3MB cache');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.ram', '8 GB  DDR3L SoDIMM 1600 MHz');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.hdd', '600 GB 5400RPM');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.graphics', 'Intel HD Graphics 5500 Integrated');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'laptop.technical.audio', '1.5W Mono');

INSERT INTO Product(id,name,type,description,img_url,price,inventory) VALUES (NEXT VALUE FOR hibernate_sequence, 'Lumia 435', 'PHONE', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet mauris semper, interdum sem lobortis, commodo magna. Donec porttitor eu sapien ac imperdiet. Aenean volutpat hendrerit purus. Donec accumsan nec arcu vel pretium. Sed erat mi, euismod at euismod quis, ultrices nec dui. Fusce commodo purus ac urna dignissim, ut eleifend ipsum sagittis. Curabitur a sapien id libero convallis porta ac nec est. Nullam vitae convallis nisl. Sed turpis velit, facilisis ac massa cursus, pellentesque tincidunt risus.', 'lumia-435.jpg', 156.99, 3);

INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.screen', '4 in 800 &times; 480');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.cpu', ' Qualcomm MSM8996');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.ram', '1 GB');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.size', '11.81 &times; 6.47 &times; 1.17 (cm)');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.cam', ' Rear 2 MP, Front 0.3 MP');

INSERT INTO Product(id,name,type,description,img_url,price,inventory) VALUES (NEXT VALUE FOR hibernate_sequence, 'LG G4', 'PHONE', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet mauris semper, interdum sem lobortis, commodo magna. Donec porttitor eu sapien ac imperdiet. Aenean volutpat hendrerit purus. Donec accumsan nec arcu vel pretium. Sed erat mi, euismod at euismod quis, ultrices nec dui. Fusce commodo purus ac urna dignissim, ut eleifend ipsum sagittis. Curabitur a sapien id libero convallis porta ac nec est. Nullam vitae convallis nisl. Sed turpis velit, facilisis ac massa cursus, pellentesque tincidunt risus.', 'lg-g4-32gb.jpg', 295.22, 5);

INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.screen', 'TFT LCD 2560 &times; 1440');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.cpu', ' Qualcomm MSM8996');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.ram', '2 GB');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.size', '14.94 &times; 7.39 &times; 0.73 (cm)');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'mobile.technical.cam', ' 16 MP, Resolution 3840 &times; 2160');

INSERT INTO Product(id,name,type,description,img_url,price,inventory) VALUES (NEXT VALUE FOR hibernate_sequence, 'Swiss Gear Top Load Laptop Case (16 in)', 'ACCESSORIES', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet mauris semper, interdum sem lobortis, commodo magna. Donec porttitor eu sapien ac imperdiet. Aenean volutpat hendrerit purus. Donec accumsan nec arcu vel pretium. Sed erat mi, euismod at euismod quis, ultrices nec dui. Fusce commodo purus ac urna dignissim, ut eleifend ipsum sagittis. Curabitur a sapien id libero convallis porta ac nec est. Nullam vitae convallis nisl. Sed turpis velit, facilisis ac massa cursus, pellentesque tincidunt risus.', 'top-load-laptop-case.jpg', 79.99, 5);

INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'accessories.technical.max_screen_size', '16 in');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'accessories.technical.dimensions', 'Width: 29.21 cm, Height: 39.37 cm, Depth: 8.25 cm');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'accessories.technical.color', 'Black, Brown');

INSERT INTO Product(id,name,type,description,img_url,price,inventory) VALUES (NEXT VALUE FOR hibernate_sequence, 'Swiss Gear Top Load Laptop Case (17.3 in)', 'ACCESSORIES', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet mauris semper, interdum sem lobortis, commodo magna. Donec porttitor eu sapien ac imperdiet. Aenean volutpat hendrerit purus. Donec accumsan nec arcu vel pretium. Sed erat mi, euismod at euismod quis, ultrices nec dui. Fusce commodo purus ac urna dignissim, ut eleifend ipsum sagittis. Curabitur a sapien id libero convallis porta ac nec est. Nullam vitae convallis nisl. Sed turpis velit, facilisis ac massa cursus, pellentesque tincidunt risus.', 'top-load-laptop-case-173.jpg', 79.99, 5);

INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'accessories.technical.max_screen_size', '17.3 in');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'accessories.technical.dimensions', 'Width: 29.21 cm, Height: 43.18 cm, Depth: 6.35 cm');
INSERT INTO product_technical_characteristics (Product_id,technical_property,properties) VALUES (CURRENT VALUE FOR hibernate_sequence, 'accessories.technical.color', 'Black');
COMMIT;